### ISSUE TITLE
More specific definition of isWordLike in the spec?

### ISSUE THREAD

**Issue by sffc** [tc39/proposal-intl-segmenter#100]
@FrankYFTang raised the issue in the March TG2 meeting that this definition is fuzzy in the spec.  We had some discussion.

**Comment by gibson042** [comment]
c6f11e058eca9a63aa62c3a645c90b5efe21abb4 collapsed a previously more direct mapping from [ICU](https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/ubrk_8h.html#af9836cc79482f82ac12eefb1f70b14b9) into a simple boolean, in part because the ICU categories are theirselves ill-defined (which I myself complained about at https://github.com/tc39/proposal-intl-segmenter/issues/44#issuecomment-484907925 ). The current state of affairs is basically this:
* [UAX #29](https://www.unicode.org/reports/tr29/) default rules describe where boundaries exist and don't exist, but don't classify segments or use properties to describe them. However, the default rules do reference character property values from [UAX #44](https://unicode.org/reports/tr44/) (e.g., [WordBreakProperty.txt](https://www.unicode.org/Public/13.0.0/ucd/auxiliary/WordBreakProperty.txt) Word_Break: *Double_Quote*, *Single_Quote*, *Hebrew_Letter*, *CR*, *LF*, *Newline*, *Extend*, *Regional_Indicator*, *Format*, *Katakana*, *ALetter*, *MidLetter*, *MidNum*, *MidNumLet*, *Numeric*, *ExtendNumLet*, *ZWJ*, *WSegSpace*, *Other*).
* ICU reports properties of _rules responsible for a boundary_, notionally as [multiple tags](http://icu-project.org/apiref/icu4j/com/ibm/icu/text/BreakIterator.html#getRuleStatusVec-int:A-) (e.g., the word segment `"A113"` might be described by both [LETTER](http://icu-project.org/apiref/icu4j/com/ibm/icu/text/BreakIterator.html#WORD_LETTER) and [NUMBER](http://icu-project.org/apiref/icu4j/com/ibm/icu/text/BreakIterator.html#WORD_NUMBER), while the sentence segment `"Why?\n"` is described by [STERM](http://icu-project.org/apiref/icu4j/com/ibm/icu/lang/UCharacter.SentenceBreak.html#STERM) and [LF](http://icu-project.org/apiref/icu4j/com/ibm/icu/lang/UCharacter.SentenceBreak.html#LF)) but [in practice](https://github.com/tc39/proposal-intl-segmenter/issues/80#issuecomment-494337045) as exclusive categories (see also https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/ubrk_8h.html#enum-members ).
* The [current definition](https://tc39.es/proposal-intl-segmenter/#sec-createsegmentdataobject) of `isWordLike` is: a Boolean value indicating whether the word segment <var>segment</var> in <var>string</var> is "word-like" according to locale <var>segmenter</var>.[[Locale]].
* The straightforward population of `isWordLike` by implementations using ICU is based upon the tags of the rule responsible for identification of an ending boundary—`false` for [WORD_NONE](https://unicode-org.github.io/icu-docs/apidoc/released/icu4j/com/ibm/icu/text/BreakIterator.html#WORD_NONE) («_Tag value for "words" that do not fit into any of other categories. Includes spaces and most punctuation._»), otherwise `true`.

Given all of the above, I'm not sure how to change the current definition, but I guess we could add a clarification like «_Segments consisting solely of spaces and most punctuation should generally not be considered "word-like"._»... would that suffice?

**Comment by gibson042** [comment]
So would you be for or against adding a clarification like «_Segments consisting solely of spaces and most punctuation should generally not be considered "word-like"._»?

**Comment by littledan** [comment]
@gibson042 I'm up for clarifications in general, but I'm not sure about that wording. Words like "spaces", "punctuation" and "should" *could* be taken to have particular strong definitions, but then at the same time, don't concretely point to their definitions. I'd be more comfortable with a note which provides an explanation of this policy as an example.
